In [15]:
import numpy as np
import pickle

In [23]:
with open('/Volumes/qhaomin/pf_mus/output/actual data, seed = 1, T = 283, N = 100000/θ_0.pkl', 'rb') as f:
            θ_1 = pickle.load(f)

In [24]:
with open('/Volumes/qhaomin/pf_mus/output/actual data, seed = 1, T = 283, N = 100000, Λ_scale = 1.0, cd_scale = 1.0/θ_0.pkl', 'rb') as f:
            θ_2 = pickle.load(f)

In [25]:
np.mean([i[0][1][0] for i in θ_1])

0.001626193175763289

In [26]:
np.mean([i[0][1][0] for i in θ_2])

8.444023600630857e-06

In [28]:
θ_1

[[array([[ 0.        ],
         [-0.64674938]]),
  array([[ 1.        ,  1.        ],
         [ 0.        , -0.36912427]]),
  array([[0.50384872, 0.        ],
         [0.        , 0.69251443]]),
  array([[ 0.        ],
         [ 0.57646467],
         [-0.50775458]]),
  array([[-0.16370944,  0.19101516, -0.42076189],
         [-0.49495278, -0.29039967, -0.27266056],
         [-0.17275444, -0.01049191, -0.48645509]]),
  array([[ 0.49416771,  0.        ,  0.        ],
         [-0.06690149,  0.43718223,  0.        ],
         [ 0.17103903, -0.11734533,  0.4292257 ]]),
  array([[ 1.        ,  0.        ,  0.        ],
         [ 0.13538216,  1.        ,  0.        ],
         [-0.30977703,  0.26841286,  1.        ]]),
  1,
  4],
 [array([[0.        ],
         [0.03185411]]),
  array([[ 1.        ,  1.        ],
         [ 0.        , -0.55437027]]),
  array([[0.7434285 , 0.        ],
         [0.        , 0.28971181]]),
  array([[ 0.        ],
         [ 0.03141481],
         [-0.4423

In [29]:
θ_2

[[array([[ 0.        ],
         [-0.07423154]]),
  array([[ 1.        ,  1.        ],
         [ 0.        , -0.24778842]]),
  array([[2.34940788, 0.        ],
         [0.        , 0.41029965]]),
  array([[0.        ],
         [0.46321729],
         [0.05721474]]),
  array([[ 0.73755637, -0.12576728, -0.22744666],
         [ 0.54935774, -0.24749032, -0.24465635],
         [ 0.24136969,  0.1708956 , -0.48012724]]),
  array([[ 1.33970234,  0.        ,  0.        ],
         [ 0.92502229,  0.86108253,  0.        ],
         [-0.20806581, -0.53310976,  0.45841488]]),
  array([[ 1.        ,  0.        ,  0.        ],
         [-0.69046852,  1.        ,  0.        ],
         [-0.27217244,  0.61911575,  1.        ]]),
  1,
  1],
 [array([[0.        ],
         [0.33890529]]),
  array([[ 1.        ,  1.        ],
         [ 0.        , -0.37480485]]),
  array([[0.80481477, 0.        ],
         [0.        , 0.62869874]]),
  array([[ 0.        ],
         [-0.42143577],
         [ 0.5234151